apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: konflux-app-test
  janus-idp.io/tekton: konflux-app-test
  backstage.io/kubernetes-id: konflux-app-test
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: konflux-app-test
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
